### ISSUE TITLE
Check formatting and grammar/spelling for use cases

### ISSUE THREAD

**Issue by brucenieh** [CMPUT301F18T21/DoctorPlzSaveMe#1]
Address Yiji's feedback:
•	Make sure multiple people look over use cases for consistent formatting and grammar/spelling
o	Ex. Use Case 19 - Basic Flow has an error, as well as Use Case 20 - Precondition, just to give a few examples

**Comment by keanweng97** [comment]
Fixed consistent formatting and grammar/spelling
Capitalized Problem, Record, Comment etc
