### ISSUE TITLE
Need explicit mapping of use cases to user stories

### ISSUE THREAD

**Issue by brucenieh** [CMPUT301F18T21/DoctorPlzSaveMe#2]
For addressing Yiji's feedback:
•	Explicit mapping of use cases to user stories would be helpful, especially for keeping track of which use cases haven’t been sufficiently covered

**Comment by keanweng97** [comment]
Done explicit mapping of use cases to user stories

**Comment by keanweng97** [comment]
Done explicit mapping of use cases to user stories
