### ISSUE TITLE
Storyboard: label actions on transitions

### ISSUE THREAD

**Issue by brucenieh** [CMPUT301F18T21/DoctorPlzSaveMe#7]
For addressing Yiji's comment "For the storyboard, there should be labeled actions on storyboard transitions. While I can still navigate through the storyboard, it would be clearer if the large overview screen displayed these labels."

**Comment by tiganov** [comment]
Not really realistic with Adobe XD. It would be a ton of work. Once we more or less finalize the Storyboard, then maybe. We got an E on the storyboard anyway.
